[project]
name = "siglip4cc"
version = "0.3.0"
description = "A Python package for vectorizing image pairs and change captioning based on SIGLIP4CC"
readme = "README.md"
authors = [
  { name = "Berkay Ates", email = "atesberkay2356@gmail.com" },
]
dependencies = [

]
